spring:
  datasource:
    url: jdbc:mysql://mysql:3306/cooperados?useSSL=false&serverTimezone=UTC
    username: root
    password: rootpass
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
server:
  port: 8080
